// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw7uIpDxnI2F7cKXm5Fh8vkmns725VTxA',
    appId: '1:1064448882522:web:1c74c7c9ae5195e4f92563',
    messagingSenderId: '1064448882522',
    projectId: 'clothes-ecommerce-99afc',
    authDomain: 'clothes-ecommerce-99afc.firebaseapp.com',
    storageBucket: 'clothes-ecommerce-99afc.firebasestorage.app',
    measurementId: 'G-84NHQ62C85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp1ClODoNaR6IjFhlTU2i8AFRBiV_2w7A',
    appId: '1:1064448882522:android:440630eceadd65d1f92563',
    messagingSenderId: '1064448882522',
    projectId: 'clothes-ecommerce-99afc',
    storageBucket: 'clothes-ecommerce-99afc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw7uIpDxnI2F7cKXm5Fh8vkmns725VTxA',
    appId: '1:1064448882522:web:37f565ae49db5adcf92563',
    messagingSenderId: '1064448882522',
    projectId: 'clothes-ecommerce-99afc',
    authDomain: 'clothes-ecommerce-99afc.firebaseapp.com',
    storageBucket: 'clothes-ecommerce-99afc.firebasestorage.app',
    measurementId: 'G-Z9P0ZW6C4N',
  );
}
